### ISSUE TITLE
Tesla isn't recognized

### ISSUE THREAD

**Issue by nnystyxx** [notjoe7F/pointersmod#13]
Using Tesla 1.10.2-1.2.1.49 (the most recent version on its curse page) and pointersmod-1.10.2-0.1-alpha.0.jar, the game gives me an error that Tesla isn't installed. Using forge 1.10.2-12.18.1.2076. No other mods installed, still causes this issue.

**Comment by branchpanic** [comment]
Thanks for submitting an issue. Will definitely fix when I get a chance tomorrow.
